name: Download Artifact
on:
  workflow_run:
    workflows: [SastScan]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: dawidd6/action-download-artifact@v2
       with:
    # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
    # Required, if artifact is from a different repo
    # Required, if repo is private a Personal Access Token with `repo` scope is needed
         github_token: ${{secrets.GITHUB_TOKEN}}
    # Required, workflow file name or ID
         workflow: SastScan
    # Optional, the status or conclusion of a completed workflow to search for
    # Can be one of a workflow conclusion:
    #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
    # Or a workflow status:
    #   "completed", "in_progress", "queued"
    #workflow_conclusion: success
    # Optional, will get head commit SHA
    #pr: ${{github.event.pull_request.number}}
    # Optional, no need to specify if PR is
    #commit: ${{github.event.pull_request.head.sha}}
    # Optional, will use the branch
         branch: main
    # Optional, defaults to all types
    #event: push
    # Optional, will use specified workflow run
    #run_id: 1122334455
    # Optional, run number from the workflow
    #run_number: 34
    # Optional, uploaded artifact name,
    # will download all artifacts if not specified
    # and extract them in respective subdirectories
    # https://github.com/actions/download-artifact#download-all-artifacts
    #name: artifact_name
    # Optional, directory where to extract artifact(s), defaults to current directory
         path: /github/workspace/reports/
    # Optional, defaults to current repo
         repo: ${{github.repository}}
    # Optional, check the workflow run whether it has an artifact
    # then will get the last available artifact from previous workflow
    # default false, just try to download from the last one
         check_artifacts:  false
    # Optional, search for the last workflow run whose stored an artifact named as in `name` input
    # default false
         search_artifacts: false
    # Optional, choose to skip unpacking the downloaded artifact(s)
    # default false
         skip_unpack: false
